// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Cliente.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EntryPoints.ReactiveWeb.Dtos {

  /// <summary>Holder for reflection information generated from Protos/Cliente.proto</summary>
  public static partial class ClienteReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Cliente.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClienteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b3MvQ2xpZW50ZS5wcm90bxIHY2xpZW50ZSJ6ChNDcmVhckNsaWVu",
            "dGVSZXF1ZXN0Eg4KBk5vbWJyZRgBIAEoCRIRCglBcGVsbGlkb3MYAiABKAkS",
            "FgoOTnVtZXJvRGVDZWR1bGEYAyABKAkSDgoGQ29ycmVvGAQgASgJEhgKEE51",
            "bWVyb0RlVGVsZWZvbm8YBSABKAkiIAoGQ2VkdWxhEhYKDk51bWVyb0RlQ2Vk",
            "dWxhGAEgASgJIlgKDENsaWVudGVSZXBseRINCgVlcnJvchgBIAEoCBIPCgdt",
            "ZXNzYWdlGAIgASgJEigKB2NsaWVudGUYAyABKAsyFy5jbGllbnRlLkNsaWVu",
            "dGVSZXF1ZXN0InUKDkNsaWVudGVSZXF1ZXN0Eg4KBk5vbWJyZRgBIAEoCRIR",
            "CglBcGVsbGlkb3MYAiABKAkSFgoOTnVtZXJvRGVDZWR1bGEYAyABKAkSDgoG",
            "Q29ycmVvGAQgASgJEhgKEE51bWVyb0RlVGVsZWZvbm8YBSABKAkiiAEKGEFj",
            "dHVhbGl6YXJDbGllbnRlUmVxdWVzdBIOCgZOb21icmUYASABKAkSEQoJQXBl",
            "bGxpZG9zGAIgASgJEg4KBkNvcnJlbxgEIAEoCRIYChBOdW1lcm9EZVRlbGVm",
            "b25vGAUgASgJEh8KBkNlZHVsYRgGIAEoCzIPLmNsaWVudGUuQ2VkdWxhMswB",
            "ChFDbGllbnRlQ29udHJvbGxlchI8CgVDcmVhchIcLmNsaWVudGUuQ3JlYXJD",
            "bGllbnRlUmVxdWVzdBoVLmNsaWVudGUuQ2xpZW50ZVJlcGx5EkYKCkFjdHVh",
            "bGl6YXISIS5jbGllbnRlLkFjdHVhbGl6YXJDbGllbnRlUmVxdWVzdBoVLmNs",
            "aWVudGUuQ2xpZW50ZVJlcGx5EjEKB09idGVuZXISDy5jbGllbnRlLkNlZHVs",
            "YRoVLmNsaWVudGUuQ2xpZW50ZVJlcGx5Qh+qAhxFbnRyeVBvaW50cy5SZWFj",
            "dGl2ZVdlYi5EdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest), global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest.Parser, new[]{ "Nombre", "Apellidos", "NumeroDeCedula", "Correo", "NumeroDeTelefono" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.ReactiveWeb.Dtos.Cedula), global::EntryPoints.ReactiveWeb.Dtos.Cedula.Parser, new[]{ "NumeroDeCedula" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.ReactiveWeb.Dtos.ClienteReply), global::EntryPoints.ReactiveWeb.Dtos.ClienteReply.Parser, new[]{ "Error", "Message", "Cliente" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.ReactiveWeb.Dtos.ClienteRequest), global::EntryPoints.ReactiveWeb.Dtos.ClienteRequest.Parser, new[]{ "Nombre", "Apellidos", "NumeroDeCedula", "Correo", "NumeroDeTelefono" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest), global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest.Parser, new[]{ "Nombre", "Apellidos", "Correo", "NumeroDeTelefono", "Cedula" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CrearClienteRequest : pb::IMessage<CrearClienteRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrearClienteRequest> _parser = new pb::MessageParser<CrearClienteRequest>(() => new CrearClienteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CrearClienteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.ReactiveWeb.Dtos.ClienteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearClienteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearClienteRequest(CrearClienteRequest other) : this() {
      nombre_ = other.nombre_;
      apellidos_ = other.apellidos_;
      numeroDeCedula_ = other.numeroDeCedula_;
      correo_ = other.correo_;
      numeroDeTelefono_ = other.numeroDeTelefono_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearClienteRequest Clone() {
      return new CrearClienteRequest(this);
    }

    /// <summary>Field number for the "Nombre" field.</summary>
    public const int NombreFieldNumber = 1;
    private string nombre_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nombre {
      get { return nombre_; }
      set {
        nombre_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Apellidos" field.</summary>
    public const int ApellidosFieldNumber = 2;
    private string apellidos_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Apellidos {
      get { return apellidos_; }
      set {
        apellidos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NumeroDeCedula" field.</summary>
    public const int NumeroDeCedulaFieldNumber = 3;
    private string numeroDeCedula_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeroDeCedula {
      get { return numeroDeCedula_; }
      set {
        numeroDeCedula_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Correo" field.</summary>
    public const int CorreoFieldNumber = 4;
    private string correo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Correo {
      get { return correo_; }
      set {
        correo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NumeroDeTelefono" field.</summary>
    public const int NumeroDeTelefonoFieldNumber = 5;
    private string numeroDeTelefono_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeroDeTelefono {
      get { return numeroDeTelefono_; }
      set {
        numeroDeTelefono_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CrearClienteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CrearClienteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nombre != other.Nombre) return false;
      if (Apellidos != other.Apellidos) return false;
      if (NumeroDeCedula != other.NumeroDeCedula) return false;
      if (Correo != other.Correo) return false;
      if (NumeroDeTelefono != other.NumeroDeTelefono) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nombre.Length != 0) hash ^= Nombre.GetHashCode();
      if (Apellidos.Length != 0) hash ^= Apellidos.GetHashCode();
      if (NumeroDeCedula.Length != 0) hash ^= NumeroDeCedula.GetHashCode();
      if (Correo.Length != 0) hash ^= Correo.GetHashCode();
      if (NumeroDeTelefono.Length != 0) hash ^= NumeroDeTelefono.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellidos);
      }
      if (NumeroDeCedula.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeroDeCedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeroDeTelefono);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellidos);
      }
      if (NumeroDeCedula.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeroDeCedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeroDeTelefono);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nombre.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombre);
      }
      if (Apellidos.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellidos);
      }
      if (NumeroDeCedula.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroDeCedula);
      }
      if (Correo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroDeTelefono);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CrearClienteRequest other) {
      if (other == null) {
        return;
      }
      if (other.Nombre.Length != 0) {
        Nombre = other.Nombre;
      }
      if (other.Apellidos.Length != 0) {
        Apellidos = other.Apellidos;
      }
      if (other.NumeroDeCedula.Length != 0) {
        NumeroDeCedula = other.NumeroDeCedula;
      }
      if (other.Correo.Length != 0) {
        Correo = other.Correo;
      }
      if (other.NumeroDeTelefono.Length != 0) {
        NumeroDeTelefono = other.NumeroDeTelefono;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellidos = input.ReadString();
            break;
          }
          case 26: {
            NumeroDeCedula = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 42: {
            NumeroDeTelefono = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellidos = input.ReadString();
            break;
          }
          case 26: {
            NumeroDeCedula = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 42: {
            NumeroDeTelefono = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Cedula : pb::IMessage<Cedula>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Cedula> _parser = new pb::MessageParser<Cedula>(() => new Cedula());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Cedula> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.ReactiveWeb.Dtos.ClienteReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cedula() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cedula(Cedula other) : this() {
      numeroDeCedula_ = other.numeroDeCedula_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cedula Clone() {
      return new Cedula(this);
    }

    /// <summary>Field number for the "NumeroDeCedula" field.</summary>
    public const int NumeroDeCedulaFieldNumber = 1;
    private string numeroDeCedula_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeroDeCedula {
      get { return numeroDeCedula_; }
      set {
        numeroDeCedula_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Cedula);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Cedula other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumeroDeCedula != other.NumeroDeCedula) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NumeroDeCedula.Length != 0) hash ^= NumeroDeCedula.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NumeroDeCedula.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumeroDeCedula);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NumeroDeCedula.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumeroDeCedula);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NumeroDeCedula.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroDeCedula);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Cedula other) {
      if (other == null) {
        return;
      }
      if (other.NumeroDeCedula.Length != 0) {
        NumeroDeCedula = other.NumeroDeCedula;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NumeroDeCedula = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NumeroDeCedula = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ClienteReply : pb::IMessage<ClienteReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClienteReply> _parser = new pb::MessageParser<ClienteReply>(() => new ClienteReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClienteReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.ReactiveWeb.Dtos.ClienteReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClienteReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClienteReply(ClienteReply other) : this() {
      error_ = other.error_;
      message_ = other.message_;
      cliente_ = other.cliente_ != null ? other.cliente_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClienteReply Clone() {
      return new ClienteReply(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private bool error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cliente" field.</summary>
    public const int ClienteFieldNumber = 3;
    private global::EntryPoints.ReactiveWeb.Dtos.ClienteRequest cliente_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.ReactiveWeb.Dtos.ClienteRequest Cliente {
      get { return cliente_; }
      set {
        cliente_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClienteReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClienteReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Error != other.Error) return false;
      if (Message != other.Message) return false;
      if (!object.Equals(Cliente, other.Cliente)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Error != false) hash ^= Error.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (cliente_ != null) hash ^= Cliente.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Error != false) {
        output.WriteRawTag(8);
        output.WriteBool(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (cliente_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Cliente);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Error != false) {
        output.WriteRawTag(8);
        output.WriteBool(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (cliente_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Cliente);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Error != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (cliente_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cliente);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClienteReply other) {
      if (other == null) {
        return;
      }
      if (other.Error != false) {
        Error = other.Error;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.cliente_ != null) {
        if (cliente_ == null) {
          Cliente = new global::EntryPoints.ReactiveWeb.Dtos.ClienteRequest();
        }
        Cliente.MergeFrom(other.Cliente);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Error = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            if (cliente_ == null) {
              Cliente = new global::EntryPoints.ReactiveWeb.Dtos.ClienteRequest();
            }
            input.ReadMessage(Cliente);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Error = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            if (cliente_ == null) {
              Cliente = new global::EntryPoints.ReactiveWeb.Dtos.ClienteRequest();
            }
            input.ReadMessage(Cliente);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ClienteRequest : pb::IMessage<ClienteRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClienteRequest> _parser = new pb::MessageParser<ClienteRequest>(() => new ClienteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClienteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.ReactiveWeb.Dtos.ClienteReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClienteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClienteRequest(ClienteRequest other) : this() {
      nombre_ = other.nombre_;
      apellidos_ = other.apellidos_;
      numeroDeCedula_ = other.numeroDeCedula_;
      correo_ = other.correo_;
      numeroDeTelefono_ = other.numeroDeTelefono_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClienteRequest Clone() {
      return new ClienteRequest(this);
    }

    /// <summary>Field number for the "Nombre" field.</summary>
    public const int NombreFieldNumber = 1;
    private string nombre_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nombre {
      get { return nombre_; }
      set {
        nombre_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Apellidos" field.</summary>
    public const int ApellidosFieldNumber = 2;
    private string apellidos_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Apellidos {
      get { return apellidos_; }
      set {
        apellidos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NumeroDeCedula" field.</summary>
    public const int NumeroDeCedulaFieldNumber = 3;
    private string numeroDeCedula_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeroDeCedula {
      get { return numeroDeCedula_; }
      set {
        numeroDeCedula_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Correo" field.</summary>
    public const int CorreoFieldNumber = 4;
    private string correo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Correo {
      get { return correo_; }
      set {
        correo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NumeroDeTelefono" field.</summary>
    public const int NumeroDeTelefonoFieldNumber = 5;
    private string numeroDeTelefono_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeroDeTelefono {
      get { return numeroDeTelefono_; }
      set {
        numeroDeTelefono_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClienteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClienteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nombre != other.Nombre) return false;
      if (Apellidos != other.Apellidos) return false;
      if (NumeroDeCedula != other.NumeroDeCedula) return false;
      if (Correo != other.Correo) return false;
      if (NumeroDeTelefono != other.NumeroDeTelefono) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nombre.Length != 0) hash ^= Nombre.GetHashCode();
      if (Apellidos.Length != 0) hash ^= Apellidos.GetHashCode();
      if (NumeroDeCedula.Length != 0) hash ^= NumeroDeCedula.GetHashCode();
      if (Correo.Length != 0) hash ^= Correo.GetHashCode();
      if (NumeroDeTelefono.Length != 0) hash ^= NumeroDeTelefono.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellidos);
      }
      if (NumeroDeCedula.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeroDeCedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeroDeTelefono);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellidos);
      }
      if (NumeroDeCedula.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeroDeCedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeroDeTelefono);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nombre.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombre);
      }
      if (Apellidos.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellidos);
      }
      if (NumeroDeCedula.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroDeCedula);
      }
      if (Correo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroDeTelefono);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClienteRequest other) {
      if (other == null) {
        return;
      }
      if (other.Nombre.Length != 0) {
        Nombre = other.Nombre;
      }
      if (other.Apellidos.Length != 0) {
        Apellidos = other.Apellidos;
      }
      if (other.NumeroDeCedula.Length != 0) {
        NumeroDeCedula = other.NumeroDeCedula;
      }
      if (other.Correo.Length != 0) {
        Correo = other.Correo;
      }
      if (other.NumeroDeTelefono.Length != 0) {
        NumeroDeTelefono = other.NumeroDeTelefono;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellidos = input.ReadString();
            break;
          }
          case 26: {
            NumeroDeCedula = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 42: {
            NumeroDeTelefono = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellidos = input.ReadString();
            break;
          }
          case 26: {
            NumeroDeCedula = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 42: {
            NumeroDeTelefono = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActualizarClienteRequest : pb::IMessage<ActualizarClienteRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActualizarClienteRequest> _parser = new pb::MessageParser<ActualizarClienteRequest>(() => new ActualizarClienteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActualizarClienteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.ReactiveWeb.Dtos.ClienteReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActualizarClienteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActualizarClienteRequest(ActualizarClienteRequest other) : this() {
      nombre_ = other.nombre_;
      apellidos_ = other.apellidos_;
      correo_ = other.correo_;
      numeroDeTelefono_ = other.numeroDeTelefono_;
      cedula_ = other.cedula_ != null ? other.cedula_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActualizarClienteRequest Clone() {
      return new ActualizarClienteRequest(this);
    }

    /// <summary>Field number for the "Nombre" field.</summary>
    public const int NombreFieldNumber = 1;
    private string nombre_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nombre {
      get { return nombre_; }
      set {
        nombre_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Apellidos" field.</summary>
    public const int ApellidosFieldNumber = 2;
    private string apellidos_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Apellidos {
      get { return apellidos_; }
      set {
        apellidos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Correo" field.</summary>
    public const int CorreoFieldNumber = 4;
    private string correo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Correo {
      get { return correo_; }
      set {
        correo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NumeroDeTelefono" field.</summary>
    public const int NumeroDeTelefonoFieldNumber = 5;
    private string numeroDeTelefono_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeroDeTelefono {
      get { return numeroDeTelefono_; }
      set {
        numeroDeTelefono_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Cedula" field.</summary>
    public const int CedulaFieldNumber = 6;
    private global::EntryPoints.ReactiveWeb.Dtos.Cedula cedula_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.ReactiveWeb.Dtos.Cedula Cedula {
      get { return cedula_; }
      set {
        cedula_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActualizarClienteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActualizarClienteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nombre != other.Nombre) return false;
      if (Apellidos != other.Apellidos) return false;
      if (Correo != other.Correo) return false;
      if (NumeroDeTelefono != other.NumeroDeTelefono) return false;
      if (!object.Equals(Cedula, other.Cedula)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nombre.Length != 0) hash ^= Nombre.GetHashCode();
      if (Apellidos.Length != 0) hash ^= Apellidos.GetHashCode();
      if (Correo.Length != 0) hash ^= Correo.GetHashCode();
      if (NumeroDeTelefono.Length != 0) hash ^= NumeroDeTelefono.GetHashCode();
      if (cedula_ != null) hash ^= Cedula.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellidos);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeroDeTelefono);
      }
      if (cedula_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Cedula);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellidos);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumeroDeTelefono);
      }
      if (cedula_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Cedula);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nombre.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombre);
      }
      if (Apellidos.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellidos);
      }
      if (Correo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Correo);
      }
      if (NumeroDeTelefono.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroDeTelefono);
      }
      if (cedula_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cedula);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActualizarClienteRequest other) {
      if (other == null) {
        return;
      }
      if (other.Nombre.Length != 0) {
        Nombre = other.Nombre;
      }
      if (other.Apellidos.Length != 0) {
        Apellidos = other.Apellidos;
      }
      if (other.Correo.Length != 0) {
        Correo = other.Correo;
      }
      if (other.NumeroDeTelefono.Length != 0) {
        NumeroDeTelefono = other.NumeroDeTelefono;
      }
      if (other.cedula_ != null) {
        if (cedula_ == null) {
          Cedula = new global::EntryPoints.ReactiveWeb.Dtos.Cedula();
        }
        Cedula.MergeFrom(other.Cedula);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellidos = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 42: {
            NumeroDeTelefono = input.ReadString();
            break;
          }
          case 50: {
            if (cedula_ == null) {
              Cedula = new global::EntryPoints.ReactiveWeb.Dtos.Cedula();
            }
            input.ReadMessage(Cedula);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellidos = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 42: {
            NumeroDeTelefono = input.ReadString();
            break;
          }
          case 50: {
            if (cedula_ == null) {
              Cedula = new global::EntryPoints.ReactiveWeb.Dtos.Cedula();
            }
            input.ReadMessage(Cedula);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
