// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Cliente.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EntryPoints.ReactiveWeb.Dtos {
  public static partial class ClienteController
  {
    static readonly string __ServiceName = "cliente.ClienteController";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest> __Marshaller_cliente_CrearClienteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.ReactiveWeb.Dtos.ClienteReply> __Marshaller_cliente_ClienteReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest> __Marshaller_cliente_ActualizarClienteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.ReactiveWeb.Dtos.Cedula> __Marshaller_cliente_Cedula = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.ReactiveWeb.Dtos.Cedula.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply> __Method_Crear = new grpc::Method<global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Crear",
        __Marshaller_cliente_CrearClienteRequest,
        __Marshaller_cliente_ClienteReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply> __Method_Actualizar = new grpc::Method<global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Actualizar",
        __Marshaller_cliente_ActualizarClienteRequest,
        __Marshaller_cliente_ClienteReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.ReactiveWeb.Dtos.Cedula, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply> __Method_Obtener = new grpc::Method<global::EntryPoints.ReactiveWeb.Dtos.Cedula, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Obtener",
        __Marshaller_cliente_Cedula,
        __Marshaller_cliente_ClienteReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EntryPoints.ReactiveWeb.Dtos.ClienteReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ClienteController</summary>
    [grpc::BindServiceMethod(typeof(ClienteController), "BindService")]
    public abstract partial class ClienteControllerBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.ReactiveWeb.Dtos.ClienteReply> Crear(global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.ReactiveWeb.Dtos.ClienteReply> Actualizar(global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.ReactiveWeb.Dtos.ClienteReply> Obtener(global::EntryPoints.ReactiveWeb.Dtos.Cedula request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ClienteControllerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Crear, serviceImpl.Crear)
          .AddMethod(__Method_Actualizar, serviceImpl.Actualizar)
          .AddMethod(__Method_Obtener, serviceImpl.Obtener).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ClienteControllerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Crear, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.ReactiveWeb.Dtos.CrearClienteRequest, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply>(serviceImpl.Crear));
      serviceBinder.AddMethod(__Method_Actualizar, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.ReactiveWeb.Dtos.ActualizarClienteRequest, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply>(serviceImpl.Actualizar));
      serviceBinder.AddMethod(__Method_Obtener, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.ReactiveWeb.Dtos.Cedula, global::EntryPoints.ReactiveWeb.Dtos.ClienteReply>(serviceImpl.Obtener));
    }

  }
}
#endregion
